#!/bin/bash
## Description: AMD Indicator Dark theme switch script
## Tested on Mint 17.3 and Catalyst (fglrx) 15.200.xxxx

# Swap the currently active icons with the Dark Themed ones
ln -sf /usr/local/amd-indicator/resources/amd-dark.png /usr/local/amd-indicator/amd.png
lm -sf /usr/local/amd-indicator/resources/intel-dark.png /usr/local/amd-indicator/intel.png
