#!/bin/bash
## Description: AMD Indicator Discrete GPU switch on script.
## Tested on Mint 17.3 and (fglrx) Catalyst 15.200.xxxx

## Use AMD Configuration Utility to switch to discrete GPU
## These commands will need to be run as sudo
amdconfig --px-dgpu

