#!/bin/bash
# Description: A straightforward logout script which uses the GNOME utilities to terminate the user session.
# Will forcefully log the user out in order for the Desktop Manager to be reinitialized.
#
# Note: This will need to be run from the current logged-in user session.
gnome-session-quit --logout --force
