#!/bin/bash
# Description: Simple script which terminates and starts a new instance of the amd-indicator application.
# Terminate all running instances of this application
pkill -f "python /usr/local/bin/amd-indicator"
# Re-run the application
/usr/local/bin/amd-indicator
